### ISSUE TITLE
Pretty recent Ruby version requirement

### ISSUE THREAD

**Issue by ordinathorreur** [dogweather/schema-dot-org#22]
I was thinking of using this library, but it requires a pretty recent version of Ruby and I'd prefer not to have to upgrade my production servers.

Is there a particular reason why it has a hard Ruby 2.6+ requirement in the gemspec?

I get this when installing:

`schema_dot_org-1.7.0 requires ruby version >= 2.6`

**Comment by dogweather** [comment]
I'd accept a PR if you'd like to add compatibility for older rubies.

**Comment by dogweather** [comment]
Closing for now as no longer relevant.
